import type { Vehicle } from '@/types'

export const VEHICLES: Vehicle[] = [
  {
    id: '1',
    slug: 'opel-mokka',
    name: 'Opel Mokka',
    nameFa: 'اوپل موکا',
    brand: 'Opel',
    model: 'Mokka',
    year: 2024,
    category: 'suv',
    status: 'available',
    fuelType: 'petrol',
    specs: {
      engine: '1.2 Turbo',
      horsepower: 130,
      torque: 230,
      acceleration_0_100: 9.1,
      topSpeed: 197,
      fuelConsumption: '6.4L/100km',
      co2Emission: 145,
      transmission: 'automatic',
      driveType: 'FWD',
      doors: 5,
      seats: 5,
      trunkVolume: 350,
      wheelbase: 2610,
    },
    colors: [
      { name: 'Moonland Grey', nameFa: 'خاکستری ماهتابی', hex: '#8B9091' },
      { name: 'Diamond Black', nameFa: 'مشکی الماسی', hex: '#1A1A1A' },
      { name: 'Summit White', nameFa: 'سفید سامیت', hex: '#F5F5F5' },
      { name: 'Voltaic Blue', nameFa: 'آبی ولتایک', hex: '#1E3A5F' },
    ],
    price: { base: 15000000000, currency: 'IRR', isNegotiable: true, showPrice: false },
    images: ['/images/mokka.webp'],
    heroImage: '/images/mokka.webp',
    thumbnailImage: '/images/mokka.webp',
    description: 'The Opel Mokka is a compact SUV that combines bold design with advanced technology.',
    descriptionFa: 'اوپل موکا یک شاسی بلند کامپکت است که طراحی جسورانه را با فناوری پیشرفته ترکیب می‌کند.',
    features: ['IntelliLink Infotainment', 'LED Matrix Headlights', 'Rear View Camera', 'Heated Seats'],
    featuresFa: ['سیستم اطلاعات سرگرمی اینتلی‌لینک', 'چراغ‌های ماتریکس LED', 'دوربین عقب', 'صندلی گرم‌شونده'],
    isFeatured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'opel-astra',
    name: 'Opel Astra',
    nameFa: 'اوپل آسترا',
    brand: 'Opel',
    model: 'Astra',
    year: 2024,
    category: 'hatchback',
    status: 'available',
    fuelType: 'petrol',
    specs: {
      engine: '1.2 Turbo',
      horsepower: 110,
      torque: 205,
      acceleration_0_100: 10.5,
      topSpeed: 188,
      fuelConsumption: '5.8L/100km',
      co2Emission: 131,
      transmission: 'manual',
      driveType: 'FWD',
      doors: 5,
      seats: 5,
      trunkVolume: 422,
      wheelbase: 2675,
    },
    colors: [
      { name: 'Arctic White', nameFa: 'سفید آرکتیک', hex: '#FFFFFF' },
      { name: 'Mineral Grey', nameFa: 'خاکستری مینرال', hex: '#6B7280' },
      { name: 'Cobalt Blue', nameFa: 'آبی کبالت', hex: '#2040A0' },
    ],
    price: { base: 12000000000, currency: 'IRR', isNegotiable: true, showPrice: false },
    images: ['/images/astra.webp'],
    heroImage: '/images/astra.webp',
    thumbnailImage: '/images/astra.webp',
    description: 'The Opel Astra: sporty design, efficient performance, and smart technology.',
    descriptionFa: 'اوپل آسترا: طراحی اسپرت، عملکرد کارآمد و فناوری هوشمند.',
    features: ['Adaptive Cruise Control', 'Lane Departure Warning', 'Apple CarPlay', 'Android Auto'],
    featuresFa: ['کروز کنترل تطبیقی', 'هشدار خروج از خط', 'اپل کارپلی', 'اندروید اتو'],
    isFeatured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'opel-mokka-e',
    name: 'Opel Mokka-e',
    nameFa: 'اوپل موکا برقی',
    brand: 'Opel',
    model: 'Mokka-e',
    year: 2024,
    category: 'suv',
    status: 'available',
    fuelType: 'electric',
    specs: {
      engine: 'Electric Motor',
      horsepower: 136,
      torque: 260,
      acceleration_0_100: 9.0,
      topSpeed: 150,
      fuelConsumption: '0L/100km',
      co2Emission: 0,
      transmission: 'automatic',
      driveType: 'FWD',
      doors: 5,
      seats: 5,
      trunkVolume: 310,
      wheelbase: 2610,
    },
    colors: [
      { name: 'Mamba Green', nameFa: 'سبز مامبا', hex: '#66CC33' },
      { name: 'Diamond Black', nameFa: 'مشکی الماسی', hex: '#1A1A1A' },
    ],
    price: { base: 18000000000, currency: 'IRR', isNegotiable: true, showPrice: false },
    images: ['/images/mokka-e.webp'],
    heroImage: '/images/mokka-e.webp',
    thumbnailImage: '/images/mokka-e.webp',
    description: 'The all-electric Opel Mokka-e. Pure energy, zero emissions.',
    descriptionFa: 'اوپل موکا برقی تمام عیار. انرژی خالص، بدون آلایندگی.',
    features: ['Electric-Specific App', 'Rapid Charging', 'Regenerative Braking', 'Quiet Cabin'],
    featuresFa: ['اپلیکیشن اختصاصی برقی', 'شارژ سریع', 'ترمز بازیاب انرژی', 'کابین بی‌صدا'],
    isFeatured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

export const STATS = [
  { value: 10, suffix: '+', labelKey: 'whyUs.stats.experience' },
  { value: 5000, suffix: '+', labelKey: 'whyUs.stats.customers' },
  { value: 3500, suffix: '+', labelKey: 'whyUs.stats.vehicles' },
  { value: 15, suffix: '', labelKey: 'whyUs.stats.agencies' },
]
