import type { OpelVehicle } from '@/types/vehicle-page'

export const MOKKA_E_DATA: OpelVehicle = {
  id: 'mokka-e',
  slug: 'mokka-e',
  brand: 'Opel',
  model: 'Mokka-e',
  year: 2024,
  bodyStyle: 'crossover',
  status: 'available',
  tagline: 'آینده‌ای کاملاً برقی',
  powertrain: {
    available: ['electric'],
    default: 'electric',
    specs: {
      electric: {
        engineCode: 'Electric 115 kW',
        displacement: '۵۴ kWh باتری',
        power: '۱۵۶ اسب بخار',
        torque: '۲۶۰ نیوتون‌متر',
        transmission: 'اتوماتیک تک‌سرعته',
        fuelConsumption: 'برقی — ۰ آلایندگی',
      },
    },
  },
  trims: [
    {
      level: 'Edition',
      displayName: 'ادیشن',
      price: 1_580_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 36_000_000, months: 36 },
      heroImage: '/images/mokka-e-photo-4.jpeg',
      features: [
        'موتور برقی ۱۵۶ اسب بخار (۱۱۵ کیلووات)',
        'باتری ۵۴ کیلووات‌ساعت (خالص ۵۰ kWh)',
        'شارژ سریع DC تا ۱۰۰ کیلووات (۲۰-۸۰٪ در ۲۷ دقیقه)',
        'شارژ AC 7.4 کیلووات (شارژ کامل ۷.۵ ساعت)',
        'Pure Panel — دو نمایشگر ۱۰ اینچ یکپارچه',
        'Apple CarPlay و Android Auto بی‌سیم',
        'دوربین دید عقب ۱۸۰ درجه',
        'ترمز اضطراری خودکار (AEB)',
        'هشدار تغییر خط',
        'سیستم کنترل ثبات خودرو (ESC)',
        'سیستم ترمز ضد قفل (ABS)',
        'کمک فنر تطبیقی FlexRide',
        'چراغ‌های جلو LED',
        'چرخ‌های آلومینیوم ۱۷ اینچ',
        'صندلی‌های گرمایشی جلو',
        'فرمان گرمایشی',
        'سیستم ورود بدون کلید',
        'شیشه‌های رنگی حریم‌خواه',
      ],
    },
    {
      level: 'GS',
      displayName: 'جی‌اس',
      price: 1_820_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 41_500_000, months: 36 },
      heroImage: '/images/mokka-e-photo-7.jpeg',
      highlightBadge: 'محبوب‌ترین',
      isRecommended: true,
      features: [
        'همه امکانات ادیشن',
        'صندلی‌های چرم ورزشی AGR',
        'چراغ‌های Pixel LED هوشمند',
        'دوربین ۳۶۰ درجه IntelliGrip',
        'رادار هشدار نقطه کور',
        'سقف دو‌رنگ کنتراست مشکی',
        'چرخ‌های آلومینیوم ۱۸ اینچ',
        'آینه‌های برقی تاشو',
        'سیستم تشخیص خستگی راننده',
      ],
    },
    {
      level: 'Ultimate',
      displayName: 'آلتیمیت',
      price: 2_100_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 47_800_000, months: 36 },
      heroImage: '/images/mokka-e-photo-2.jpeg',
      features: [
        'همه امکانات جی‌اس',
        'صندلی‌های چرم ماساژور گرمایشی و خنک‌کننده',
        'سانروف پانوراما برقی',
        'سیستم صوتی پریمیوم ۱۰ بلندگو',
        'پارک خودکار کامل IntelliGrip',
        'OpelConnect نامحدود ۵ ساله',
        'کروز کنترل تطبیقی با توقف و حرکت',
        'نمایشگر HUD روی شیشه جلو',
      ],
    },
  ],
  colors: [
    {
      id: 'black',
      name: 'مشکی شب',
      nameEn: 'Midnight Black',
      hex: '#0A0A0A',
      image: '/images/mokka-e-photo-4.jpeg',
      available: true,
    },
    {
      id: 'white',
      name: 'سفید مروارید',
      nameEn: 'Pearl White',
      hex: '#F5F5F5',
      image: '/images/mokka-e-photo-7.jpeg',
      available: true,
    },
    {
      id: 'blue',
      name: 'آبی کبالت',
      nameEn: 'Cobalt Blue',
      hex: '#1A3A6B',
      image: '/images/mokka-e-photo-3.jpeg',
      available: true,
    },
    {
      id: 'grey',
      name: 'خاکستری تیتانیوم',
      nameEn: 'Titanium Grey',
      hex: '#6B6B6B',
      image: '/images/mokka-e-photo-4.jpeg',
      available: false,
      availableSoon: true,
    },
  ],
  specs: {
    dimensions: {
      length: 4151,
      width: 1790,
      height: 1534,
      wheelbase: 2561,
      trunkVolume: 310,
      weight: 1598,
    },
    performance: {
      topSpeed: 150,
      acceleration0100: 9.0,
      range: 403,
    },
    safety: {
      euroncap: 5,
      airbags: 6,
      features: [
        'ترمز اضطراری خودکار',
        'رادار هشدار نقطه کور',
        'هشدار تغییر خط',
        'سیستم تشخیص تصادف',
        'دوربین ۱۸۰ درجه عقب',
        'پایش ۳۶۰ درجه راننده',
      ],
    },
    technology: {
      screenSize: '۱۰"',
      appleCarPlay: true,
      androidAuto: true,
      camera360: true,
      adaptiveCruise: true,
      laneAssist: true,
    },
  },
  media: {
    heroImage: '/images/mokka-e-photo-4.jpeg',
    gallery: [
      { url: '/images/mokka-e-photo-4.jpeg', alt: 'اوپل موکا E — نمای جلو' },
      { url: '/images/mokka-e-photo-7.jpeg', alt: 'اوپل موکا E — نمای عقب' },
      { url: '/images/mokka-e-photo-3.jpeg', alt: 'اوپل موکا E — در نمایشگاه' },
      { url: '/images/mokka-e-photo-2.jpeg', alt: 'اوپل موکا E — نمای جانبی' },
      { url: '/images/mokka-e-photo-1.jpeg', alt: 'اوپل موکا E — جلو پارک' },
      { url: '/images/mokka-e-photo-6.jpeg', alt: 'اوپل موکا E — تمام زوایا' },
      { url: '/images/mokka-e-photo-5.jpeg', alt: 'اوپل موکا E — در حرکت' },
    ],
    exterior: [
      {
        url: '/images/mokka-e-photo-4.jpeg',
        alt: 'اوپل موکا E — طراحی جلو برقی',
        callouts: [
          { label: 'Pixel LED برقی',   top: '30%', right: '22%' },
          { label: 'گریل بسته برقی',   top: '55%', right: '35%' },
          { label: 'نشان برقی سبز',    top: '58%', left: '32%' },
        ],
      },
      {
        url: '/images/mokka-e-photo-7.jpeg',
        alt: 'اوپل موکا E — طراحی عقب',
        callouts: [
          { label: 'چراغ‌های LED عقب',  top: '35%', left: '20%' },
          { label: 'لترینگ MOKKA-E',    top: '48%', right: '28%' },
        ],
      },
      {
        url: '/images/mokka-e-photo-6.jpeg',
        alt: 'اوپل موکا E — چهار زاویه',
      },
    ],
    interior: [
      {
        url: '/images/mokka-e-photo-2.jpeg',
        alt: 'اوپل موکا E — کابین Pure Panel',
        caption: 'Pure Panel — دو نمایشگر ۱۰ اینچ یکپارچه',
      },
      {
        url: '/images/mokka-e-photo-1.jpeg',
        alt: 'اوپل موکا E — داشبورد و فرمان',
        caption: 'فرمان ورزشی با کنترل صوتی و صفحات کنترل',
      },
    ],
  },

  highlights: [
    {
      number: '۰۱',
      titleFa: 'صفر انتشار کربن',
      titleEn: 'Zero Emissions',
      descFa: 'موتور برقی ۱۵۶ اسب بخار با باتری ۵۴ کیلووات‌ساعت — رانندگی پاک بدون هیچ سازش.',
      image: '/images/mokka-e-photo-4.jpeg',
    },
    {
      number: '۰۲',
      titleFa: 'شارژ سریع ۲۷ دقیقه',
      titleEn: 'Fast Charge 27 min',
      descFa: 'شارژگر سریع DC تا ۱۰۰ کیلووات: از ۲۰٪ به ۸۰٪ تنها در ۲۷ دقیقه. شارژ شبانه AC در ۷.۵ ساعت.',
      image: '/images/mokka-e-photo-3.jpeg',
    },
    {
      number: '۰۳',
      titleFa: 'Pure Panel کابین',
      titleEn: 'Pure Panel Cockpit',
      descFa: 'دو نمایشگر ۱۰ اینچ یکپارچه در قابی خطی — اینفوتینمنت آینده‌نگر با Apple CarPlay بی‌سیم.',
      image: '/images/mokka-e-photo-2.jpeg',
    },
    {
      number: '۰۴',
      titleFa: 'برد ۴۰۳ کیلومتر WLTP',
      titleEn: '403 km WLTP Range',
      descFa: 'تا ۴۰۳ کیلومتر در چرخه WLTP — سفر طولانی‌مدت بدون استرس برد.',
      image: '/images/mokka-e-photo-5.jpeg',
    },
    {
      number: '۰۵',
      titleFa: 'ایمنی ۵ ستاره',
      titleEn: '5-Star Safety',
      descFa: 'رتبه ۵ ستاره Euro NCAP، ۶ کیسه هوا، ترمز اضطراری خودکار، و سیستم پایش کامل راننده.',
      image: '/images/mokka-e-photo-7.jpeg',
    },
  ],
  seo: {
    titleFa: 'اوپل موکا E ۲۰۲۴ | خودروی برقی | سیکاس خودرو',
    descriptionFa:
      'خرید اوپل موکا E ۲۰۲۴ با بهترین قیمت در ایران. خودروی برقی ۱۵۶ اسب بخار، باتری ۵۴ kWh، شارژ سریع DC. گارانتی رسمی سیکاس خودرو.',
    keywords: ['اوپل موکا ای', 'موکا E', 'خودرو برقی اوپل', 'Opel Mokka-E Iran', 'قیمت موکا E'],
  },
  dealers: [
    {
      id: 'tehran-1',
      name: 'نمایندگی تهران',
      city: 'تهران',
      address: 'تهران، بلوار آفریقا، خیابان جهان‌آرا',
      phone: '021-88001234',
      lat: 35.6892,
      lng: 51.3890,
      stock: 3,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
    {
      id: 'isfahan-1',
      name: 'نمایندگی اصفهان',
      city: 'اصفهان',
      address: 'اصفهان، خیابان چهارباغ عباسی',
      phone: '031-36001234',
      lat: 32.6539,
      lng: 51.6660,
      stock: 2,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
    {
      id: 'mashhad-1',
      name: 'نمایندگی مشهد',
      city: 'مشهد',
      address: 'مشهد، بلوار وکیل‌آباد',
      phone: '051-38001234',
      lat: 36.2605,
      lng: 59.6168,
      stock: 1,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
  ],
  importInfo: {
    originCountry: 'آلمان',
    warrantyYears: 3,
    warrantyKm: 100000,
    serviceCenterCount: 28,
    registrationInfo:
      'تمامی خودروهای اوپل وارداتی توسط سیکاس خودرو از طریق گمرک رسمی جمهوری اسلامی ایران ترخیص می‌شوند.',
  },
}
