import type { OpelVehicle } from '@/types/vehicle-page'

export const ASTRA_DATA: OpelVehicle = {
  id: 'astra',
  slug: 'astra',
  brand: 'Opel',
  model: 'Astra',
  year: 2025,
  bodyStyle: 'hatchback',
  status: 'available',
  tagline: 'هیجان در هر خیابان',
  powertrain: {
    available: ['petrol'],
    default: 'petrol',
    specs: {
      petrol: {
        engineCode: '1.2 DI Turbo',
        displacement: '۱۱۹۹ سی‌سی',
        power: '۱۳۰ اسب بخار',
        torque: '۲۳۰ نیوتون‌متر',
        transmission: 'اتوماتیک ۸ سرعته DCT',
        fuelConsumption: '۵.۷ لیتر/۱۰۰کم',
      },
    },
  },
  trims: [
    {
      level: 'Edition',
      displayName: 'ادیشن',
      price: 1_150_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 26_200_000, months: 36 },
      heroImage: '/images/astra-new.png',
      features: [
        'نمایشگر ۱۰.۲۵ اینچ لمسی',
        'دوربین دنده عقب',
        'Apple CarPlay و Android Auto',
        'سیستم صوتی ۶ بلندگو',
        'ترمز اضطراری خودکار',
        'هشدار تغییر خط',
      ],
    },
    {
      level: 'GS',
      displayName: 'جی‌اس',
      price: 1_380_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 31_400_000, months: 36 },
      heroImage: '/images/astra-2024.webp',
      highlightBadge: 'محبوب‌ترین',
      isRecommended: true,
      features: [
        'همه امکانات ادیشن',
        'سقف دوتن مشکی',
        'صندلی‌های ورزشی چرم',
        'دوربین ۳۶۰ درجه',
        'چراغ‌های Matrix LED',
        'تمپومات تطبیقی',
      ],
    },
    {
      level: 'Ultimate',
      displayName: 'آلتیمیت',
      price: 1_620_000_000,
      installment: { downPaymentPercent: 30, monthlyPayment: 36_900_000, months: 36 },
      heroImage: '/images/astra-hero.webp',
      features: [
        'همه امکانات جی‌اس',
        'صندلی‌های ماساژور',
        'سانروف پانوراما',
        'سیستم صوتی ۱۰ بلندگو',
        'پارک خودکار کامل',
        'OpelConnect نامحدود',
      ],
    },
  ],
  colors: [
    {
      id: 'white',
      name: 'سفید مرواریدی',
      nameEn: 'Summit White',
      hex: '#F2F0EC',
      image: '/images/astra-new.png',
      available: true,
    },
    {
      id: 'black',
      name: 'مشکی آبنوس',
      nameEn: 'Ebony Black',
      hex: '#1A1A1A',
      image: '/images/astra-new.png',
      available: true,
    },
    {
      id: 'red',
      name: 'قرمز اوپال',
      nameEn: 'Magma Red',
      hex: '#CC2200',
      image: '/images/astra-new.png',
      available: true,
    },
    {
      id: 'blue',
      name: 'آبی سارفیر',
      nameEn: 'Sapphire Blue',
      hex: '#1B4B8C',
      image: '/images/astra-new.png',
      available: true,
    },
  ],
  specs: {
    dimensions: {
      length: 4374,
      width: 1860,
      height: 1430,
      wheelbase: 2675,
      trunkVolume: 422,
    },
    performance: {
      topSpeed: 206,
      acceleration0100: 9.1,
    },
    safety: {
      euroncap: 5,
      airbags: 6,
      features: [
        'ترمز اضطراری خودکار',
        'هشدار تغییر خط',
        'هشدار نقطه کور',
        'کمک نگهداری خط',
      ],
    },
    technology: {
      screenSize: '۱۰.۲۵"',
      appleCarPlay: true,
      androidAuto: true,
      camera360: true,
      adaptiveCruise: true,
      laneAssist: true,
    },
  },
  media: {
    heroImage: '/images/astra-hero.webp',
    gallery: [
      { url: '/images/astra-2024.webp', alt: 'اوپل آسترا ۲۰۲۵' },
      { url: '/images/astra-banner-new.jpg', alt: 'اوپل آسترا ۲۰۲۵ نمای جانبی' },
    ],
  },
  seo: {
    titleFa: 'اوپل آسترا ۲۰۲۵ | قیمت و مشخصات | سیکاس خودرو',
    descriptionFa: 'خرید اوپل آسترا ۲۰۲۵ با بهترین قیمت در ایران. سه تریم با شرایط اقساطی ویژه و گارانتی رسمی.',
    keywords: ['اوپل آسترا', 'قیمت آسترا ۲۰۲۵', 'Opel Astra Iran'],
  },
  dealers: [
    {
      id: 'tehran-1',
      name: 'نمایندگی تهران',
      city: 'تهران',
      address: 'تهران، بلوار آفریقا، خیابان جهان‌آرا',
      phone: '021-88001234',
      lat: 35.6892,
      lng: 51.3890,
      stock: 4,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
    {
      id: 'isfahan-1',
      name: 'نمایندگی اصفهان',
      city: 'اصفهان',
      address: 'اصفهان، خیابان چهارباغ عباسی',
      phone: '031-36001234',
      lat: 32.6539,
      lng: 51.6660,
      stock: 2,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
    {
      id: 'mashhad-1',
      name: 'نمایندگی مشهد',
      city: 'مشهد',
      address: 'مشهد، بلوار وکیل‌آباد',
      phone: '051-38001234',
      lat: 36.2605,
      lng: 59.6168,
      stock: 3,
      hours: 'شنبه تا چهارشنبه ۹-۱۸، پنج‌شنبه ۹-۱۴',
    },
  ],
  importInfo: {
    originCountry: 'آلمان',
    warrantyYears: 3,
    warrantyKm: 100000,
    serviceCenterCount: 28,
    registrationInfo:
      'تمامی خودروهای اوپل وارداتی توسط سیکاس خودرو از طریق گمرک رسمی جمهوری اسلامی ایران ترخیص می‌شوند.',
  },
}
